# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/www/www_cpu/www_cpu.srcs/sources_1/ip/imem_1/imem.xci
# IP: The module: 'imem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/www/www_cpu/www_cpu.srcs/sources_1/ip/imem_1/imem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'imem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/www/www_cpu/www_cpu.srcs/sources_1/ip/imem_1/imem.xci
# IP: The module: 'imem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/www/www_cpu/www_cpu.srcs/sources_1/ip/imem_1/imem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'imem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
